###############################################################
# 10 - Terraform (plan on branches, apply on main)
# Purpose:
#  - Use GitHub OIDC to assume AWS role (no static keys).
#  - Plan on branches/PRs; Apply only on main push.
#  - Protect apply with GitHub Environment "production" (set reviewers).
###############################################################
name: 10 - Terraform (plan on branches, apply on main)

on:
  push:                       # ← Run on pushes (feature/*, develop, release/*, hotfix/*, main)
    branches: ["**"]
  pull_request:               # ← Also run on PRs (plans only)
    branches: ["**"]

permissions:
  id-token: write             # ← Needed for OIDC to assume role
  contents: read              # ← Needed to checkout

concurrency:
  group: terraform-${{ github.ref_name }}     # ← One run per branch name
  cancel-in-progress: true                    # ← Cancel older run on new push

jobs:
  tf:
    runs-on: ubuntu-latest

    # Apply is gated by environment protections (Settings → Environments → production)
    # Only set environment when it's a PUSH to main; PRs & other branches are not gated.
    environment: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' && 'production' || '' }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5

      - name: Preflight — verify Variables (OIDC mode)
        shell: bash
        run: |
          set -eu
          [ -n "${{ vars.AWS_REGION }}" ]      || { echo "Missing variable: AWS_REGION"; exit 1; }
          [ -n "${{ vars.AWS_ROLE_ARN }}" ]    || { echo "Missing variable: AWS_ROLE_ARN"; exit 1; }
          [ -n "${{ vars.TF_STATE_BUCKET }}" ] || { echo "Missing variable: TF_STATE_BUCKET"; exit 1; }
          [ -n "${{ vars.TF_STATE_TABLE }}" ] || { echo "Missing variable: TF_STATE_TABLE"; exit 1; }
          [ -n "${{ vars.TF_STATE_KEY }}" ] || { echo "Missing variable: TF_STATE_KEY"; exit 1; }
          if [[ ! "${{ vars.AWS_REGION }}" =~ ^[a-z]+-[a-z]+-[0-9]+$ ]]; then
            echo "Invalid AWS_REGION: '${{ vars.AWS_REGION }}'"; exit 1
          fi
          echo "Preflight OK."

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3           # ← Pinned Terraform CLI

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume:   ${{ vars.AWS_ROLE_ARN }}  # ← Role created by bootstrap
          aws-region:       ${{ vars.AWS_REGION }}
          role-session-name: gha-tf-${{ github.run_id }}

      - name: Sanity — whoami
        run: aws sts get-caller-identity

      - name: Terraform Init (S3 backend only) + Workspace
        shell: bash
        run: |
          terraform init -input=false             -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}"             -backend-config="key=${{ vars.TF_STATE_KEY }}"             -backend-config="region=${{ vars.AWS_REGION }}"             -backend-config="dynamodb_table=${{ vars.TF_STATE_TABLE }}"             -backend-config="encrypt=true"

          terraform workspace list || true
          terraform workspace select "$WS" || terraform workspace new "$WS"

      - name: Terraform fmt & validate & plan
        env:
          TF_VAR_region: ${{ vars.AWS_REGION }}
        run: |
          terraform fmt -check
          terraform validate
          terraform plan -input=false -no-color -lock=false -out=tfplan.bin

      - name: Upload plan artifact (for non-main branches)
        if: github.ref != 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan.bin
          retention-days: 7

      - name: Terraform Apply (only on main; gated by environment)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          TF_VAR_region: ${{ vars.AWS_REGION }}
        run: terraform apply -input=false -auto-approve -lock=false tfplan.bin
